### ISSUE TITLE
pre-commit has changed from hooks.yaml -> .pre-commit-hooks.yaml

### ISSUE THREAD

**Issue by asottile** [guykisel/pre-commit-robotframework-tidy#1]
Hello pre-commit hook implementer!

In version 0.12.0 pre-commit has changed the default location for the file formerly known as `hooks.yaml` to make it more convincing for others to add more hooks.

As such, a migration has to (unfortunately) occur.

For maximum compatibility it is suggested to `cp hooks.yaml .pre-commit-hooks.yaml` (at least for the migration period).  A copy is suggested over a symlink unless you do not care for windows compatibility (and I wouldn't blame you!).

Once the migration period is over (or you no longer care to support old versions of pre-commit), the hooks.yaml file is no longer necessary and may be deleted.

See https://github.com/pre-commit/pre-commit/pull/470 for more details

Thanks again for contributing to the pre-commit ecosystem, we couldn't do it without you :)
Anthony

**Comment by asottile** [comment]
This repository has been temporarily removed from [pre-commit.com](http://pre-commit.com/hooks.html) as the latest version of pre-commit (0.16.0) has removed support for legacy `hooks.yaml`.  Without providing `.pre-commit-hooks.yaml`, users will be unable to use this hook repository with `pre-commit>=0.16.0`.

**Comment by henryykt** [comment]
#2

**Comment by guykisel** [comment]
fixed in https://github.com/guykisel/pre-commit-robotframework-tidy/pull/2

**Comment by asottile** [comment]
re-enabled in the hooks page :tada: https://github.com/pre-commit/pre-commit.github.io/commit/bb9ea8e8f8c17cd0bf66abb75008e8bce3501e2b
